format_version: 10
pipelines:
  TESTE-01:
    group: microservicos
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-225f0d6:
        git: https://github.com/barceloscbc/poc-container
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:nFb7SHCnUjLwiLFjPoHxnA==:+4FCB2SrlEjmWEZZeQr2ig==
    stages:
    - build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build_image:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
              id: nexus-bcr
              store_id: nexus-private
              configuration:
                options:
                  image: ${DOCKERHUB_USERNAME}/nexus-bcr
                  Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
              arguments:
              - -c
              - docker build -t ${DOCKERHUB_USERNAME}/nexus-bcr:$GO_PIPELINE_LABEL
              command: /bin/bash
              run_if: passed
